/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as DecksIndexRouteImport } from "./routes/decks/index"
import { Route as CollectionIndexRouteImport } from "./routes/collection/index"
import { Route as CardsIndexRouteImport } from "./routes/cards/index"
import { Route as DecksIdRouteImport } from "./routes/decks/$id"
import { Route as CollectionNewRouteImport } from "./routes/collection/new"
import { Route as CardsIdRouteImport } from "./routes/cards/$id"
import { Route as ShareDecksTokenRouteImport } from "./routes/share/decks/$token"
import { Route as DecksIdPlaytestRouteImport } from "./routes/decks_.$id.playtest"
import { Route as CollectionLocationsIdRouteImport } from "./routes/collection/locations/$id"
import { Route as CollectionIdEditRouteImport } from "./routes/collection/$id.edit"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: "/decks/",
  path: "/decks/",
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: "/collection/",
  path: "/collection/",
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: "/cards/",
  path: "/cards/",
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIdRoute = DecksIdRouteImport.update({
  id: "/decks/$id",
  path: "/decks/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionNewRoute = CollectionNewRouteImport.update({
  id: "/collection/new",
  path: "/collection/new",
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIdRoute = CardsIdRouteImport.update({
  id: "/cards/$id",
  path: "/cards/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const ShareDecksTokenRoute = ShareDecksTokenRouteImport.update({
  id: "/share/decks/$token",
  path: "/share/decks/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIdPlaytestRoute = DecksIdPlaytestRouteImport.update({
  id: "/decks_/$id/playtest",
  path: "/decks/$id/playtest",
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionLocationsIdRoute = CollectionLocationsIdRouteImport.update({
  id: "/collection/locations/$id",
  path: "/collection/locations/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdEditRoute = CollectionIdEditRouteImport.update({
  id: "/collection/$id/edit",
  path: "/collection/$id/edit",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/settings": typeof SettingsRoute
  "/cards/$id": typeof CardsIdRoute
  "/collection/new": typeof CollectionNewRoute
  "/decks/$id": typeof DecksIdRoute
  "/cards/": typeof CardsIndexRoute
  "/collection/": typeof CollectionIndexRoute
  "/decks/": typeof DecksIndexRoute
  "/collection/$id/edit": typeof CollectionIdEditRoute
  "/collection/locations/$id": typeof CollectionLocationsIdRoute
  "/decks/$id/playtest": typeof DecksIdPlaytestRoute
  "/share/decks/$token": typeof ShareDecksTokenRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/settings": typeof SettingsRoute
  "/cards/$id": typeof CardsIdRoute
  "/collection/new": typeof CollectionNewRoute
  "/decks/$id": typeof DecksIdRoute
  "/cards": typeof CardsIndexRoute
  "/collection": typeof CollectionIndexRoute
  "/decks": typeof DecksIndexRoute
  "/collection/$id/edit": typeof CollectionIdEditRoute
  "/collection/locations/$id": typeof CollectionLocationsIdRoute
  "/decks/$id/playtest": typeof DecksIdPlaytestRoute
  "/share/decks/$token": typeof ShareDecksTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/settings": typeof SettingsRoute
  "/cards/$id": typeof CardsIdRoute
  "/collection/new": typeof CollectionNewRoute
  "/decks/$id": typeof DecksIdRoute
  "/cards/": typeof CardsIndexRoute
  "/collection/": typeof CollectionIndexRoute
  "/decks/": typeof DecksIndexRoute
  "/collection/$id/edit": typeof CollectionIdEditRoute
  "/collection/locations/$id": typeof CollectionLocationsIdRoute
  "/decks_/$id/playtest": typeof DecksIdPlaytestRoute
  "/share/decks/$token": typeof ShareDecksTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/settings"
    | "/cards/$id"
    | "/collection/new"
    | "/decks/$id"
    | "/cards/"
    | "/collection/"
    | "/decks/"
    | "/collection/$id/edit"
    | "/collection/locations/$id"
    | "/decks/$id/playtest"
    | "/share/decks/$token"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/settings"
    | "/cards/$id"
    | "/collection/new"
    | "/decks/$id"
    | "/cards"
    | "/collection"
    | "/decks"
    | "/collection/$id/edit"
    | "/collection/locations/$id"
    | "/decks/$id/playtest"
    | "/share/decks/$token"
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/cards/$id"
    | "/collection/new"
    | "/decks/$id"
    | "/cards/"
    | "/collection/"
    | "/decks/"
    | "/collection/$id/edit"
    | "/collection/locations/$id"
    | "/decks_/$id/playtest"
    | "/share/decks/$token"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  CardsIdRoute: typeof CardsIdRoute
  CollectionNewRoute: typeof CollectionNewRoute
  DecksIdRoute: typeof DecksIdRoute
  CardsIndexRoute: typeof CardsIndexRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
  DecksIndexRoute: typeof DecksIndexRoute
  CollectionIdEditRoute: typeof CollectionIdEditRoute
  CollectionLocationsIdRoute: typeof CollectionLocationsIdRoute
  DecksIdPlaytestRoute: typeof DecksIdPlaytestRoute
  ShareDecksTokenRoute: typeof ShareDecksTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decks/": {
      id: "/decks/"
      path: "/decks"
      fullPath: "/decks/"
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/collection/": {
      id: "/collection/"
      path: "/collection"
      fullPath: "/collection/"
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cards/": {
      id: "/cards/"
      path: "/cards"
      fullPath: "/cards/"
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decks/$id": {
      id: "/decks/$id"
      path: "/decks/$id"
      fullPath: "/decks/$id"
      preLoaderRoute: typeof DecksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/collection/new": {
      id: "/collection/new"
      path: "/collection/new"
      fullPath: "/collection/new"
      preLoaderRoute: typeof CollectionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cards/$id": {
      id: "/cards/$id"
      path: "/cards/$id"
      fullPath: "/cards/$id"
      preLoaderRoute: typeof CardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/share/decks/$token": {
      id: "/share/decks/$token"
      path: "/share/decks/$token"
      fullPath: "/share/decks/$token"
      preLoaderRoute: typeof ShareDecksTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decks_/$id/playtest": {
      id: "/decks_/$id/playtest"
      path: "/decks/$id/playtest"
      fullPath: "/decks/$id/playtest"
      preLoaderRoute: typeof DecksIdPlaytestRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/collection/locations/$id": {
      id: "/collection/locations/$id"
      path: "/collection/locations/$id"
      fullPath: "/collection/locations/$id"
      preLoaderRoute: typeof CollectionLocationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/collection/$id/edit": {
      id: "/collection/$id/edit"
      path: "/collection/$id/edit"
      fullPath: "/collection/$id/edit"
      preLoaderRoute: typeof CollectionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  CardsIdRoute: CardsIdRoute,
  CollectionNewRoute: CollectionNewRoute,
  DecksIdRoute: DecksIdRoute,
  CardsIndexRoute: CardsIndexRoute,
  CollectionIndexRoute: CollectionIndexRoute,
  DecksIndexRoute: DecksIndexRoute,
  CollectionIdEditRoute: CollectionIdEditRoute,
  CollectionLocationsIdRoute: CollectionLocationsIdRoute,
  DecksIdPlaytestRoute: DecksIdPlaytestRoute,
  ShareDecksTokenRoute: ShareDecksTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
